name: music_login
description: A simple Flutter music app sign-in UI with API health check
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  convex_bottom_bar: ^3.2.0
  rounded_bottom_bar_flutter: ^0.0.1
  just_audio: ^0.9.35
  provider: ^6.0.5
  marquee: ^2.3.0
  audio_session: ^0.1.6
  shimmer: ^3.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
    # Put your brand assets here if you have them
    # - assets/images/logo.png




