// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj-pkXZY8SqUIU2vyMf6kEjowb7XGva6U',
    appId: '1:140491875189:web:d04ab1582dd81e1ab5a93c',
    messagingSenderId: '140491875189',
    projectId: 'thongbaodacn',
    authDomain: 'thongbaodacn.firebaseapp.com',
    storageBucket: 'thongbaodacn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvzCMqWMctPIdYi4wGQ0uVsjbtuFH8bU',
    appId: '1:140491875189:android:9e75fd3a14e2ffc0b5a93c',
    messagingSenderId: '140491875189',
    projectId: 'thongbaodacn',
    storageBucket: 'thongbaodacn.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj-pkXZY8SqUIU2vyMf6kEjowb7XGva6U',
    appId: '1:140491875189:web:8855425acd942115b5a93c',
    messagingSenderId: '140491875189',
    projectId: 'thongbaodacn',
    authDomain: 'thongbaodacn.firebaseapp.com',
    storageBucket: 'thongbaodacn.firebasestorage.app',
  );
}
